### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by HaleAT** [fossildog117/Coding_Curriculum#28]

**Comment by HaleAT** [comment]
I was thinking perhaps this could be done as a series of challenges on a single page, so they set up functions for adding, deleting and so on and each of them is tested as in the sorting pages and then they set up a function which takes a symbol (e.g. '*', or '/') and two numbers and applies the correct function as they will be loaded from the previous challenges and then this is called by a graphical calculator.

**Comment by pjude2016** [comment]
Calculator tasks has been created.
